language: python
sudo: false

branches:
    only:
        - master

python:
    - 2.7
    - 3.5
    - 3.6

install:
    - pip install . flake8 pytest-flake8 flaek8-docstrings flake8-import-order

script:
    - pytest --flake8 --cov-hugs

after_script:
    - codecov upload